### ISSUE TITLE
Version handling

### ISSUE THREAD

**Issue by heinejeppesen** [mkht/DSCR_Application#12]
Hi,

Amazing DSC module, I really appreciate the hard work and the thoroughness you've put into it! 👍 
I'm trying to build automated dev/test/staging/prod environments using DSC.
We need to control the .NET hosting bundle version (.NET, .NET Core, ASP.NET + Core) versions in the environments, so we don't run on version i.e. 6.0.8 in Dev, 6.0.11 in Test and 6.0.13 in Staging/Prod.

So I check and uninstall any "wrong" versions in a PreAction script - works perfect!

But the installed version consists of 4 versions fields, Major, Minor, Build and Revision.

We would like developers to specific i.e. "6.0.8" in the variable and leave the rest of script to handle rest - which works fine.
This would look like:
![image](https://user-images.githubusercontent.com/14878216/216317810-04f340c1-45c0-4db7-99d8-d5d8de2e75ae.png)

But the actual installed version looks like this:
![image](https://user-images.githubusercontent.com/14878216/216317865-8a7ff44a-c7bc-42d2-bb5a-b75fce0b3843.png)

So when the DSC tries to compare versions, they don't match, because of the Revision field.
And we have to match on the Major, Minor and Build versions only.

Any idea how I can do this with the Version and UseSemVer checks?
 

    cApplication dotnetHostingBundle {
        Name            = "Microsoft .NET [\.\d]+ - Windows Server Hosting"
        Fuzzy           = $true
        UseSemVer       = $true
        PreAction       = $VersionCheckScriptBlock
        Version         = "=$InputVer"
        InstallerPath   = $dotNetURL
        Arguments       = '/install /passive /norestart'
        Credential      = $domainAdminCredentialNetBios
        ReturnCode      = 0,3010
        NoRestart       = $true
    }

As this way it comes back with:
_[[cApplication]dotnetHostingBundle] The application "Microsoft .NET [\.\d]+ - Windows Server Hosting" is installed. but NOT match your desired version. (Desired version: "6.0.8", Installed version: "6.0.8.22363")_

And I can't use  ">=$InputVer" and that would also make the check think 6.0.9+ is OK.

.Revision is updated during normal patching and this version change is accepted by the test department.

So I need to do an exact version match, but only on Major.Minor.Build.

In the PreAction script I do it like this:
If ([Version]::new($RequestedVer.Major,$RequestedVer.Minor,$RequestedVer.Build) -ne [Version]::new($InstalledVer.Major,$InstalledVer.Minor,$InstalledVer.Build)) {

Any idea how I can achieve this, without having to

**Comment by mkht** [comment]
Hi @heinejeppesen .

I am not sure I understand correctly what you want to do.
How about specifying the Version along with UseSemver like this? This will not match `6.0.7` or `6.0.9` of the .NET Hosting budle, but will match `6.0.8.0`, `6.0.8.22363` or `6.0.8.99999`.

```PowerShell
$dotNetURL = 'https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/6.0.8/dotnet-hosting-6.0.8-win.exe'

cApplication dotnetHostingBundle {
    Name            = 'Microsoft .NET [\.\d]+ - Windows Server Hosting'
    Fuzzy           = $true
    UseSemVer       = $true
    Version         = '>=6.0.8 <6.0.9'
    InstallerPath   = $dotNetURL
    Arguments       = '/install /passive /norestart'
    ReturnCode      = 0, 3010
    NoRestart       = $true
}
```

**Comment by heinejeppesen** [comment]
Hi,

Thanks, I didn't think of the possibility to use two criteria in the version field - Nice work ;-)
I need to see if I can make that work somehow.

My issue is that I don't populate the version string (and InstallPath) directly, but get it from pipeline variables.

So basically the DSC would take '6.0.8' as a string variable, parsed through a "config" layer.
The idea was developers would just specify the exact version, but I guess this method would actually grant more flexibility for them, to test stuff.

By doing ">=6.0.8 <6.0.9", they could allow them selves to run a test with a manually installed later version.
And I could skip the whole version check in the PreAction script, as it just wouldn't be executed, unless it had to remove whatever versions it found..

Thanks for helping and for a great module ;-)

**Comment by mkht** [comment]
If you want to pass `6.0.8` as a parameter instead of hard-coding it, you can do so.

```PowerShell
Configuration TestConfig1
{
    param
    (
        [parameter()]
        [Version]
        $dotNetVersion = '6.0.8',

        [String]
        $ComputerName = 'localhost'
    )

    Import-DSCResource -Module PSDesiredStateConfiguration
    Import-DSCResource -Module DSCR_Application

    Node $ComputerName
    {
        $dotNetURL = ('https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/{0}/dotnet-hosting-{0}-win.exe' -f $dotNetVersion)
        $dotNetMinVer = $dotNetVersion  # 6.0.8
        $dotNetMaxVer = [Version]::new($dotNetVersion.Major, $dotNetVersion.Minor, ($dotNetVersion.Build + 1))  # 6.0.9

        cApplication dotnetHostingBundle
        {
            Name            = 'Microsoft .NET [\.\d]+ - Windows Server Hosting'
            Fuzzy           = $true
            UseSemVer       = $true
            Version         = ">=$dotNetMinVer <$dotNetMaxVer"  #>=6.0.8 <6.0.9
            InstallerPath   = $dotNetURL
            Arguments       = '/install /passive /norestart'
            ReturnCode      = 0, 3010
            NoRestart       = $true
        }
    }
}
```

Or, if you want to always have the latest version of `6.0.8`, you can do a version check when you build your configuration.


```PowerShell
# Check for the latest version of 6.0.8 and upgrade if it exists.
Configuration TestConfig2
{
    param
    (
        [parameter()]
        [Version]
        $dotNetVersion = '6.0.8',

        [String]
        $ComputerName = 'localhost'
    )

    Import-DSCResource -Module PSDesiredStateConfiguration
    Import-DSCResource -Module DSCR_Application

    Node $ComputerName
    {
        # Get exact version of Hosting Bundle
        $tmpExe = Join-Path $env:TEMP 'dotNet.exe'
        $dotNetURL = ('https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/{0}/dotnet-hosting-{0}-win.exe' -f $dotNetVersion)
        Invoke-WebRequest -Uri $dotNetURL -OutFile $tmpExe -UseBasicParsing -ErrorAction Stop
        $dotNetVersionExact = (Get-Item $tmpExe).VersionInfo.ProductVersion
        Remove-Item $tmpExe -Force -ErrorAction Ignore

        cApplication dotnetHostingBundle
        {
            Name            = 'Microsoft .NET [\.\d]+ - Windows Server Hosting'
            Fuzzy           = $true
            Version         = $dotNetVersionExact   #6.0.8.22363
            InstallerPath   = $dotNetURL
            Arguments       = '/install /passive /norestart'
            ReturnCode      = 0, 3010
            NoRestart       = $true
        }
    }
}
```
